"""Proposal assembly for Core Audit v1.1.

Assembles a validated :class:`models.Proposal` from:

* a reviewed :class:`models.Scorecard`
* an approved :class:`models.FindingsCollection`

Deliverables and exclusions are drawn from the locked package-to-scope
tables in this module. They are not invented or generated by an LLM \u2014
the ``recommended_package`` from the scorecard is the anchor, and the
findings inform the scope summary sentence.

Locked decisions carried forward:

* ``recommended_package`` comes from the scorecard unchanged.
* Deliverables and exclusions are explicit, per-package, and not hallucinated.
* Scope summary is grounded in the audit score, band, and finding count.
* No scoring or routing logic lives here.
"""

from __future__ import annotations

from datetime import datetime, timezone

from . import models as M

# ---------------------------------------------------------------------------
# Locked package-to-scope tables
# ---------------------------------------------------------------------------

#: Locked deliverables list per recommended package.
#: Extend in a later phase if scope expands \u2014 do not change package names.
PACKAGE_DELIVERABLES: dict[str, list[str]] = {
    "Full Rebuild": [
        "Workspace architecture assessment and redesign plan",
        "Consolidated database structure with clear relational schema",
        "Rebuilt core workflows with consistent naming and ownership",
        "Page hierarchy and navigation restructure",
        "Governance framework and team onboarding documentation",
        "Post-rebuild workspace walkthrough session",
    ],
    "Partial Rebuild": [
        "Targeted database consolidation and schema cleanup",
        "Workflow redesign for identified weak areas",
        "Views and dashboards refresh aligned with rebuilt structures",
        "Structural gap closure for flagged audit categories",
        "Post-rebuild review session",
    ],
    "Governance Add-on": [
        "Intake process design and request workflow build",
        "Governance and ownership framework documentation",
        "Team usage guide and naming convention standards",
        "Review and cleanup of orphaned or duplicate pages",
        "Governance review session",
    ],
    "Optimization Sprint": [
        "Views and dashboard refinement across key databases",
        "Naming and tagging consistency cleanup",
        "Quick-win workflow improvements identified in the audit",
        "Recommendations for ongoing maintenance practices",
        "Optimization review session",
    ],
    "Automation / AI Add-on": [
        "Workflow automation design and implementation",
        "AI-assisted views or summary integrations",
        "Trigger and template setup for recurring processes",
        "Documentation of automated flows for team handover",
        "Automation walkthrough session",
    ],
    "No immediate major project needed": [
        "Maintenance review and minor refinement recommendations",
        "Forward-looking roadmap for future workspace growth",
    ],
}

#: Locked exclusions list per recommended package.
PACKAGE_EXCLUSIONS: dict[str, list[str]] = {
    "Full Rebuild": [
        "Data migration from external systems (addressed separately if required)",
        "Notion API integrations or third-party tool connections",
        "Ongoing content population after rebuild completion",
        "Training beyond a single post-delivery walkthrough",
    ],
    "Partial Rebuild": [
        "Areas of the workspace identified as out-of-scope in the audit",
        "Full workspace restructure beyond the flagged categories",
        "Notion API integrations or third-party tool connections",
    ],
    "Governance Add-on": [
        "Structural database redesign (not in scope \u2014 core structure is healthy)",
        "Custom automation or AI integrations",
        "Content population or data entry",
    ],
    "Optimization Sprint": [
        "Database schema changes or structural redesign",
        "Governance framework build (separate engagement if required)",
        "Notion API integrations or third-party tool connections",
    ],
    "Automation / AI Add-on": [
        "Structural database redesign (workspace must be in solid condition)",
        "Custom external API or webhook development beyond standard Notion features",
        "Ongoing automation maintenance beyond initial handover documentation",
    ],
    "No immediate major project needed": [
        "No major structural engagement is proposed based on audit results",
    ],
}

# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def _scope_summary(
    package: str,
    scorecard: M.Scorecard,
    fc: M.FindingsCollection,
) -> str:
    """Compose a grounded scope summary from structured audit inputs."""
    n = len(fc.findings)
    high_count = sum(
        1 for f in fc.findings if (f.severity or "") in ("critical", "high")
    )
    finding_phrase = f"{n} finding{'s' if n != 1 else ''}"
    if high_count:
        finding_phrase += f" ({high_count} high or critical severity)"

    return (
        f"Based on a Core Audit v1.1 overall score of {scorecard.overall_score} "
        f"({scorecard.maturity_band}), the recommended engagement is a {package}. "
        f"The audit identified {finding_phrase}. "
        f"This engagement is scoped to address the priority gaps confirmed in the "
        f"reviewed audit findings and is not expanded beyond the reviewed audit scope."
    )


# ---------------------------------------------------------------------------
# Top-level assembly
# ---------------------------------------------------------------------------


def assemble_proposal(
    audit_id: str,
    scorecard: M.Scorecard,
    fc: M.FindingsCollection,
) -> M.Proposal:
    """Assemble a structured :class:`models.Proposal` from approved inputs.

    ``recommended_package`` is taken directly from the scorecard. Deliverables
    and exclusions are drawn from the locked package-to-scope tables in this
    module. The scope summary is grounded in the audit score, band, and
    finding count \u2014 no content is invented.

    Args:
        audit_id: The audit identifier.
        scorecard: Validated scorecard artifact.
        fc: Approved findings collection.

    Returns:
        A validated :class:`models.Proposal` ready for serialization.
    """
    package = scorecard.recommended_package
    return M.Proposal(
        audit_id=audit_id,
        recommended_package=M.RecommendedPackage(package),
        scope_summary=_scope_summary(package, scorecard, fc),
        deliverables=list(PACKAGE_DELIVERABLES.get(package, [])),
        exclusions=list(PACKAGE_EXCLUSIONS.get(package, [])),
        generated_at=datetime.now(timezone.utc),
    )


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def render_proposal_markdown(proposal: M.Proposal) -> str:
    """Render a :class:`models.Proposal` as a Markdown string.

    Derived solely from the structured ``proposal`` object. No additional
    facts are introduced. Suitable for client review and later delivery.
    """
    generated = (
        proposal.generated_at.isoformat(timespec="seconds")
        if hasattr(proposal.generated_at, "isoformat")
        else str(proposal.generated_at)
    )
    lines: list[str] = [
        f"# Engagement Proposal \u2014 {proposal.audit_id}",
        "",
        f"_Generated: {generated}_",
        "",
        "---",
        "",
        "## Recommended Package",
        "",
        f"**{proposal.recommended_package}**",
        "",
        "---",
        "",
        "## Scope Summary",
        "",
        proposal.scope_summary,
        "",
        "---",
        "",
        "## Deliverables",
        "",
    ]
    if proposal.deliverables:
        for d in proposal.deliverables:
            lines.append(f"- {d}")
        lines.append("")
    else:
        lines += ["_(none specified)_", ""]

    lines += ["---", "", "## Exclusions", ""]
    if proposal.exclusions:
        for e in proposal.exclusions:
            lines.append(f"- {e}")
        lines.append("")
    else:
        lines += ["_(none specified)_", ""]

    return "\n".join(lines)


__all__ = [
    "PACKAGE_DELIVERABLES",
    "PACKAGE_EXCLUSIONS",
    "assemble_proposal",
    "render_proposal_markdown",
]
